### ISSUE TITLE
Strings and integers

### ISSUE THREAD

**Issue by jahluwalia** [isa-group/oas-tools#102]
HI,

If i have the following swagger definition:

```yaml
paths:
  /object-by-id:
    get:
        description: Returns a object to caller
        operationId: get
        x-swagger-router-controller: object
        parameters:
          - in: path
            name: id
            description: The id of the object to retrieve
            required: true
            schema:
                type: string
```

The id is a hex string. So that could mean it's `"3a5bc5de"` which works fine. However, because the id is a hex string, it's perfectly valid to have something like `"12345678"`

In the second case I get something like:

```json
[
  {
    "message": "Wrong parameter id in params. ",
    "error": [
      {
        "code": "INVALID_TYPE",
        "params": [
          "string",
          "integer"
        ],
        "message": "Expected type string but found type integer",
        "path": "#/"
      }
    ]
  }
]
```

So then I tried adding pattern to the string as follows:

```yaml
paths:
  /object-by-id:
    get:
        description: Returns a object to caller
        operationId: get
        x-swagger-router-controller: object
        parameters:
          - in: path
            name: id
            description: The id of the object to retrieve
            required: true
            schema:
                type: string
                pattern: '[0-9a-fA-F]+'
```

I still got the same error. Can you guys shed some light on 1) why it's treating my id parameter as a number in some cases and 2) why pattern isn't supported?

Thanks,
Jas
