### ISSUE TITLE
Validation breaks when 'example: null' in Component Schema property

### ISSUE THREAD

**Issue by DJFarr** [isa-group/oas-tools#193]
Here is an example of my component schema, where i was using an example to show that some nullable properties could be recieved as null.

I believe this is valid, according to editor.swagger.io, however, if its not I'd appreciate a heads up.
```
components:
  schemas:
    Test:
      required:
        - prop_1
        - prop_2
      type: object
      properties:
        prop_1:
          type: string
          nullable: true
          example: LoanName
        prop_2:
          type: string
          nullable: true
          example: null     <<<<<   here
```

Basically, when the example is of type null, it breaks in the src/lib/utils.js in the fixNullable recursive method. 

```
var fixNullable = function(schema) {
  Object.getOwnPropertyNames(schema).forEach((property) => {
    if (typeof schema[property] === 'object') {
      fixNullable(schema[property]);
    } else if (property === 'type' && typeof schema[property] === 'string' && schema.nullable === true) {
      schema.type = [schema.type, "null"];
    }
  });
}
```

```
(node:20628) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at fixNullable (c:\Users\me\project\node_modules\oas-tools\src\lib\utils.js:26:10)
    at Object.getOwnPropertyNames.forEach (c:\Users\me\project\node_modules\oas-tools\src\lib\utils.js:28:7)
    at Array.forEach (<anonymous>)
    at fixNullable (c:\Users\me\project\node_modules\oas-tools\src\lib\utils.js:26:38)
    at Object.getOwnPropertyNames.forEach (c:\Users\me\project\node_modules\oas-tools\src\lib\utils.js:28:7)
    at Array.forEach (<anonymous>)
    at fixNullable (c:\Users\me\project\node_modules\oas-tools\src\lib\utils.js:26:38)
    at Object.getOwnPropertyNames.forEach (c:\Users\me\project\node_modules\oas-tools\src\lib\utils.js:28:7)
    at Array.forEach (<anonymous>)
(node:20628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```
