### ISSUE TITLE
Strings is incorrectly converted to integers 

### ISSUE THREAD

**Issue by stefan-jonasson** [isa-group/oas-tools#206]
If the OAS spec is an array of strings, there is a JSON.parse that will convert the value to a number. 
This can lead to subtitle bugs that are hard to find. 

### Using this definition:
```
 /arrayWithStringsTest:
    get:
      parameters:
        - name: listTestParam
          in: query
         required: true
          schema:
            type: array
            items:
              type: string
```
### Result with one param 
```/arrayWithStringsTest?listTestParam=123 => [123]```

### Result with several params:
```/arrayWithStringsTest?listTestParam=123&listTestParam=124 => ["123", "124"]```
