### ISSUE TITLE
Can not get swagger metadata

### ISSUE THREAD

**Issue by caolan-ibm** [isa-group/oas-tools#247]
I used to use swagger-tools 0.10.4 and it works to get the metadata defined in swagger.yaml, but in oas-tools, it did not work.

1. defined a 'x-swagger-roles' which is different for different API operations in the swagger yaml file.
```
paths:
  /xxx:
     x-swagger-router-controller: xxx
     post:
        x-swagger-roles: [admin, operator]
```
2. initializedMiddleware
```
oasTools.initializeMiddleware(oasDoc, app, (middleware) => {
  app.use(middleware.swaggerMetadata());
}
```

3. try to get this 'x-swagger-roles' for API request, but when I debug this, req.swagger is null
```
async function verifyAPIkey(req, _authOrSecDef, scopesOrApiKey, callback) {
  const roles = req.swagger.operation['x-swagger-roles'];  // req.swagger is null
}
```
