### ISSUE TITLE
[BUG] oneof yaml specification is not valid json 

### ISSUE THREAD

**Issue by johonIngka** [isa-group/oas-tools#370]
When migrating fro oas v2 to @oas-tools-core our old oas.yaml config file is no longer valid. 
Using oneOf / anyOf configuration in yaml config fails with message: "SyntaxError: Unexpected token u in JSON at position 0". The error is only thrown when the response is send and validated, not when starting the server and validating the oas specification. 

example: 
     
 ```
  Response:
      type: object
        properties:
          message:
            anyOf:
              - type: object
              - type: array
              - type: string
```
I have also tried an alternative just to list all the valid types, but that is not valid either. 
```
     Response:
        type: object
        properties:
          message:       
            type: 
              - string
              - array
              - object
```
Using newest version of oas-tools-core, yam file and openapi: "3.0.0" ( I also tried openapi: "3.1.0")

Any suggestion, is this no longer valid syntax and what is the best alternative?

UPDATE: 
The issue seems related to 'array' type that requires an items definition. So the following solution works: 
          
          anyOf:
            - type: string
            - type: array
              items:
                type: object
            - type: object
            -

As a solution it would be usefull if this is failing already in the validation of the OAS spec file or if a better error message is thrown.
