### ISSUE TITLE
[SUGESTION] Remove check of multiple http security schemes

### ISSUE THREAD

**Issue by mikelax** [isa-group/oas-tools#383]
## **Is your feature request related to a problem? Please describe.**
It appears that in the upgrade to 3.0 version there was a [check added that prevents more than one](https://github.com/oas-tools/oas-tools/blob/622df71deeb7ab5d03ce3f8dd7ce4e7bec8aaf71/src/middleware/native/oas-security.js#L28-L34) `http` security scheme from being added to an Operation.  [Here is the original commit](https://github.com/oas-tools/oas-tools/commit/51df89918c3ccc2cab94efc7d162d2fd7a133c1f) with the change. 

I am confused what problem or situation this check is preventing or solving. 

**Describe the solution you'd like**
I would like to go back to the 2.x implementation that did allow for multiple `http` security schemes to be applied on an Operation. I have a use case where I have different security handlers for "admin-level" APIs vs. regular end-user APIs. There are of course some APIs that are able to be accessed by both user types. 

```yaml
paths:
  /foo:
    get:
      operationId: getFoo
      security:
        #any authenticated user
        - bearerSelfAuth: []
        - bearerAdminAuth: []
```

This allows for reusable functions for doing checks like looking for certain roles and/or scopes, etc. Can the check be removed, or at the very least refactored to restrict multiple `http` schemes in the same logical `AND` block. 

For example this would be valid:  

```yaml
paths:
  /foo:
    get:
      operationId: getFoo
      security:
        #any authenticated user
        - bearerHttpAuth1: []
        - bearerHttpAuth2: []
```

While this would *not* be valid:

```yaml
paths:
  /foo:
    get:
      operationId: getFoo
      security:
        #any authenticated user
        - bearerHttpAuth1: []
          bearerHttpAuth2: []
        - ApiKeyAuth1: []
```

## **Describe alternatives you've considered**
Without removing this check, I would be forced to refactor these separate functions into one larger, more complex security handler. 

**Additional context**
N/A
