### ISSUE TITLE
Bug in validating headers

### ISSUE THREAD

**Issue by davegrix** [isa-group/oas-tools#66]
I am running into an error where I am hitting the error on line 136 of oas-validator.

Relevant yaml

```
/branch/:deviceID:
    get:
      x-router-controller: secure
      tags:
        - secure
      summary: gets branch details
      operationId: getBranch
      description: Returns a array of objects of branch
      parameters:
        - in: header
          name: X-deviceToken
          schema:
            type: string
          required: true
        - in: path
          name: deviceID
          schema:
            type: string
          required: true
```

It looks like req[location][name] is always returned undefined when this is in header

> curl -X GET "http://localhost:3000/branch/:deviceID" -H "accept: application/json" -H "X-deviceToken: asdasd"

```
console.log(params[i])

{ in: 'header',
  name: 'X-deviceToken',
  schema: { type: 'string' },
  required: true }
{ in: 'path',
  name: 'deviceID',
  schema: { type: 'string' },
  required: true }

console.log(location)
header
params

console.log(req[location][name])
undefined
:deviceID

```
